/*
 * Copyright (c) 2021 BarrelMC Team
 * This project is licensed under the MIT License
 */

package org.barrelmc.barrel.network.converter;

public class BlockConverter {

    // Convert mc bedrock block ids to java block state id
    public static int toJavaStateId(int blockId) {
        int stateId = 1;

        // hehe pls help me :) (generated by the beautiful PHP language)
        if (blockId == 0) {
            stateId = 0;
        } else if (blockId == 1) {
            stateId = 1;
        } else if (blockId == 2) {
            stateId = 9;
        } else if (blockId == 3) {
            stateId = 10;
        } else if (blockId == 4) {
            stateId = 14;
        } else if (blockId == 5) {
            stateId = 15;
        } else if (blockId == 6) {
            stateId = 21;
        } else if (blockId == 7) {
            stateId = 33;
        } else if (blockId == 9) {
            stateId = 34;
        } else if (blockId == 11) {
            stateId = 50;
        } else if (blockId == 12) {
            stateId = 66;
        } else if (blockId == 13) {
            stateId = 68;
        } else if (blockId == 14) {
            stateId = 69;
        } else if (blockId == 15) {
            stateId = 70;
        } else if (blockId == 16) {
            stateId = 71;
        } else if (blockId == 17) {
            stateId = 74;
        } else if (blockId == 18) {
            stateId = 158;
        } else if (blockId == 19) {
            stateId = 229;
        } else if (blockId == 20) {
            stateId = 231;
        } else if (blockId == 21) {
            stateId = 232;
        } else if (blockId == 22) {
            stateId = 233;
        } else if (blockId == 23) {
            stateId = 235;
        } else if (blockId == 24) {
            stateId = 246;
        } else if (blockId == 25) {
            stateId = 250;
        } else if (blockId == 26) {
            stateId = 1052;
        } else if (blockId == 28) {
            stateId = 1323;
        } else if (blockId == 29) {
            stateId = 1335;
        } else if (blockId == 30) {
            stateId = 1341;
        } else if (blockId == 31) {
            stateId = 1342;
        } else if (blockId == 32) {
            stateId = 1344;
        } else if (blockId == 33) {
            stateId = 1354;
        } else if (blockId == 35) {
            stateId = 1384;
        } else if (blockId == 37) {
            stateId = 1412;
        } else if (blockId == 38) {
            stateId = 1413;
        } else if (blockId == 39) {
            stateId = 1425;
        } else if (blockId == 40) {
            stateId = 1426;
        } else if (blockId == 41) {
            stateId = 1427;
        } else if (blockId == 42) {
            stateId = 1428;
        } else if (blockId == 44) {
            stateId = 8343;
        } else if (blockId == 46) {
            stateId = 1431;
        } else if (blockId == 47) {
            stateId = 1432;
        } else if (blockId == 48) {
            stateId = 1433;
        } else if (blockId == 49) {
            stateId = 1434;
        } else if (blockId == 50) {
            stateId = 1435;
        } else if (blockId == 51) {
            stateId = 1471;
        } else if (blockId == 52) {
            stateId = 1953;
        } else if (blockId == 53) {
            stateId = 1965;
        } else if (blockId == 54) {
            stateId = 2035;
        } else if (blockId == 55) {
            stateId = 3218;
        } else if (blockId == 56) {
            stateId = 3354;
        } else if (blockId == 57) {
            stateId = 3355;
        } else if (blockId == 58) {
            stateId = 3356;
        } else if (blockId == 59) {
            stateId = 3357;
        } else if (blockId == 60) {
            stateId = 3365;
        } else if (blockId == 61) {
            stateId = 3374;
        } else if (blockId == 64) {
            stateId = 3584;
        } else if (blockId == 65) {
            stateId = 3638;
        } else if (blockId == 66) {
            stateId = 3645;
        } else if (blockId == 67) {
            stateId = 10164;
        } else if (blockId == 69) {
            stateId = 3792;
        } else if (blockId == 70) {
            stateId = 3808;
        } else if (blockId == 71) {
            stateId = 3820;
        } else if (blockId == 72) {
            stateId = 3874;
        } else if (blockId == 73) {
            stateId = 3886;
        } else if (blockId == 76) {
            stateId = 3887;
        } else if (blockId == 77) {
            stateId = 3906;
        } else if (blockId == 78) {
            stateId = 3921;
        } else if (blockId == 79) {
            stateId = 3929;
        } else if (blockId == 80) {
            stateId = 3930;
        } else if (blockId == 81) {
            stateId = 3931;
        } else if (blockId == 82) {
            stateId = 3947;
        } else if (blockId == 84) {
            stateId = 3965;
        } else if (blockId == 85) {
            stateId = 3997;
        } else if (blockId == 86) {
            stateId = 3998;
        } else if (blockId == 87) {
            stateId = 3999;
        } else if (blockId == 88) {
            stateId = 4000;
        } else if (blockId == 89) {
            stateId = 4013;
        } else if (blockId == 92) {
            stateId = 4024;
        } else if (blockId == 96) {
            stateId = 4126;
        } else if (blockId == 98) {
            stateId = 4495;
        } else if (blockId == 99) {
            stateId = 4505;
        } else if (blockId == 100) {
            stateId = 4569;
        } else if (blockId == 101) {
            stateId = 4728;
        } else if (blockId == 102) {
            stateId = 4766;
        } else if (blockId == 103) {
            stateId = 4767;
        } else if (blockId == 104) {
            stateId = 4776;
        } else if (blockId == 105) {
            stateId = 4784;
        } else if (blockId == 106) {
            stateId = 4823;
        } else if (blockId == 107) {
            stateId = 4831;
        } else if (blockId == 108) {
            stateId = 4867;
        } else if (blockId == 109) {
            stateId = 4947;
        } else if (blockId == 110) {
            stateId = 5017;
        } else if (blockId == 112) {
            stateId = 5019;
        } else if (blockId == 113) {
            stateId = 5051;
        } else if (blockId == 114) {
            stateId = 5063;
        } else if (blockId == 115) {
            stateId = 5132;
        } else if (blockId == 116) {
            stateId = 5136;
        } else if (blockId == 117) {
            stateId = 5144;
        } else if (blockId == 118) {
            stateId = 5145;
        } else if (blockId == 119) {
            stateId = 5149;
        } else if (blockId == 120) {
            stateId = 5154;
        } else if (blockId == 121) {
            stateId = 5158;
        } else if (blockId == 122) {
            stateId = 5159;
        } else if (blockId == 123) {
            stateId = 5161;
        } else if (blockId == 125) {
            stateId = 6840;
        } else if (blockId == 126) {
            stateId = 6833;
        } else if (blockId == 127) {
            stateId = 5162;
        } else if (blockId == 128) {
            stateId = 5185;
        } else if (blockId == 129) {
            stateId = 5254;
        } else if (blockId == 130) {
            stateId = 5256;
        } else if (blockId == 131) {
            stateId = 5272;
        } else if (blockId == 133) {
            stateId = 5407;
        } else if (blockId == 134) {
            stateId = 5419;
        } else if (blockId == 135) {
            stateId = 5499;
        } else if (blockId == 136) {
            stateId = 5579;
        } else if (blockId == 137) {
            stateId = 5654;
        } else if (blockId == 138) {
            stateId = 5660;
        } else if (blockId == 139) {
            stateId = 5664;
        } else if (blockId == 140) {
            stateId = 6309;
        } else if (blockId == 141) {
            stateId = 6334;
        } else if (blockId == 142) {
            stateId = 6342;
        } else if (blockId == 143) {
            stateId = 6359;
        } else if (blockId == 144) {
            stateId = 6494;
        } else if (blockId == 145) {
            stateId = 6614;
        } else if (blockId == 146) {
            stateId = 6627;
        } else if (blockId == 147) {
            stateId = 6650;
        } else if (blockId == 148) {
            stateId = 6666;
        } else if (blockId == 151) {
            stateId = 6714;
        } else if (blockId == 152) {
            stateId = 6730;
        } else if (blockId == 153) {
            stateId = 6731;
        } else if (blockId == 154) {
            stateId = 6732;
        } else if (blockId == 155) {
            stateId = 6742;
        } else if (blockId == 156) {
            stateId = 6758;
        } else if (blockId == 158) {
            stateId = 8307;
        } else if (blockId == 160) {
            stateId = 6898;
        } else if (blockId == 163) {
            stateId = 7390;
        } else if (blockId == 164) {
            stateId = 7470;
        } else if (blockId == 165) {
            stateId = 7539;
        } else if (blockId == 167) {
            stateId = 7556;
        } else if (blockId == 168) {
            stateId = 7605;
        } else if (blockId == 169) {
            stateId = 7866;
        } else if (blockId == 170) {
            stateId = 7868;
        } else if (blockId == 171) {
            stateId = 7870;
        } else if (blockId == 173) {
            stateId = 7887;
        } else if (blockId == 174) {
            stateId = 7888;
        } else if (blockId == 179) {
            stateId = 8221;
        } else if (blockId == 180) {
            stateId = 8235;
        } else if (blockId == 183) {
            stateId = 8429;
        } else if (blockId == 184) {
            stateId = 8461;
        } else if (blockId == 185) {
            stateId = 8493;
        } else if (blockId == 186) {
            stateId = 8557;
        } else if (blockId == 187) {
            stateId = 8525;
        } else if (blockId == 188) {
            stateId = 9235;
        } else if (blockId == 189) {
            stateId = 9247;
        } else if (blockId == 193) {
            stateId = 8753;
        } else if (blockId == 194) {
            stateId = 8817;
        } else if (blockId == 195) {
            stateId = 8881;
        } else if (blockId == 196) {
            stateId = 8945;
        } else if (blockId == 197) {
            stateId = 9009;
        } else if (blockId == 198) {
            stateId = 9227;
        } else if (blockId == 200) {
            stateId = 9132;
        } else if (blockId == 201) {
            stateId = 9138;
        } else if (blockId == 203) {
            stateId = 9153;
        } else if (blockId == 206) {
            stateId = 9222;
        } else if (blockId == 207) {
            stateId = 9253;
        } else if (blockId == 208) {
            stateId = 9066;
        } else if (blockId == 209) {
            stateId = 9228;
        } else if (blockId == 213) {
            stateId = 9257;
        } else if (blockId == 214) {
            stateId = 9258;
        } else if (blockId == 215) {
            stateId = 9259;
        } else if (blockId == 216) {
            stateId = 9261;
        } else if (blockId == 217) {
            stateId = 9263;
        } else if (blockId == 218) {
            stateId = 9280;
        } else if (blockId == 219) {
            stateId = 9418;
        } else if (blockId == 220) {
            stateId = 9378;
        } else if (blockId == 221) {
            stateId = 9382;
        } else if (blockId == 222) {
            stateId = 9386;
        } else if (blockId == 223) {
            stateId = 9390;
        } else if (blockId == 224) {
            stateId = 9394;
        } else if (blockId == 225) {
            stateId = 9398;
        } else if (blockId == 226) {
            stateId = 9402;
        } else if (blockId == 227) {
            stateId = 9406;
        } else if (blockId == 229) {
            stateId = 9414;
        } else if (blockId == 231) {
            stateId = 9422;
        } else if (blockId == 232) {
            stateId = 9426;
        } else if (blockId == 233) {
            stateId = 9430;
        } else if (blockId == 234) {
            stateId = 9434;
        } else if (blockId == 235) {
            stateId = 9438;
        } else if (blockId == 236) {
            stateId = 9442;
        } else if (blockId == 237) {
            stateId = 9458;
        } else if (blockId == 240) {
            stateId = 9131;
        } else if (blockId == 241) {
            stateId = 4095;
        } else if (blockId == 243) {
            stateId = 13;
        } else if (blockId == 244) {
            stateId = 9223;
        } else if (blockId == 251) {
            stateId = 9269;
        } else if (blockId == 252) {
            stateId = 15743;
        } else if (blockId == 257) {
            stateId = 7619;
        } else if (blockId == 258) {
            stateId = 7779;
        } else if (blockId == 260) {
            stateId = 92;
        } else if (blockId == 261) {
            stateId = 95;
        } else if (blockId == 262) {
            stateId = 98;
        } else if (blockId == 263) {
            stateId = 101;
        } else if (blockId == 264) {
            stateId = 104;
        } else if (blockId == 265) {
            stateId = 107;
        } else if (blockId == 266) {
            stateId = 9652;
        } else if (blockId == 385) {
            stateId = 1345;
        } else if (blockId == 393) {
            stateId = 9474;
        } else if (blockId == 394) {
            stateId = 9501;
        } else if (blockId == 395) {
            stateId = 6455;
        } else if (blockId == 396) {
            stateId = 6407;
        } else if (blockId == 397) {
            stateId = 6479;
        } else if (blockId == 398) {
            stateId = 6431;
        } else if (blockId == 399) {
            stateId = 6383;
        } else if (blockId == 400) {
            stateId = 4382;
        } else if (blockId == 401) {
            stateId = 4254;
        } else if (blockId == 402) {
            stateId = 4446;
        } else if (blockId == 403) {
            stateId = 4318;
        } else if (blockId == 404) {
            stateId = 4190;
        } else if (blockId == 405) {
            stateId = 3882;
        } else if (blockId == 406) {
            stateId = 3878;
        } else if (blockId == 407) {
            stateId = 3884;
        } else if (blockId == 408) {
            stateId = 3880;
        } else if (blockId == 409) {
            stateId = 3876;
        } else if (blockId == 410) {
            stateId = 4016;
        } else if (blockId == 411) {
            stateId = 9644;
        } else if (blockId == 412) {
            stateId = 9653;
        } else if (blockId == 414) {
            stateId = 9502;
        } else if (blockId == 415) {
            stateId = 9671;
        } else if (blockId == 416) {
            stateId = 7540;
        } else if (blockId == 418) {
            stateId = 9656;
        } else if (blockId == 419) {
            stateId = 9655;
        } else if (blockId == 420) {
            stateId = 14790;
        } else if (blockId == 424) {
            stateId = 10404;
        } else if (blockId == 425) {
            stateId = 10724;
        } else if (blockId == 426) {
            stateId = 10484;
        } else if (blockId == 427) {
            stateId = 9684;
        } else if (blockId == 428) {
            stateId = 9924;
        } else if (blockId == 429) {
            stateId = 10644;
        } else if (blockId == 430) {
            stateId = 9844;
        } else if (blockId == 431) {
            stateId = 9764;
        } else if (blockId == 432) {
            stateId = 10244;
        } else if (blockId == 433) {
            stateId = 10084;
        } else if (blockId == 434) {
            stateId = 10004;
        } else if (blockId == 437) {
            stateId = 3744;
        } else if (blockId == 438) {
            stateId = 8418;
        } else if (blockId == 439) {
            stateId = 10564;
        } else if (blockId == 440) {
            stateId = 10324;
        } else if (blockId == 442) {
            stateId = 3752;
        } else if (blockId == 444) {
            stateId = 3768;
        } else if (blockId == 446) {
            stateId = 3760;
        } else if (blockId == 449) {
            stateId = 14840;
        } else if (blockId == 450) {
            stateId = 14829;
        } else if (blockId == 451) {
            stateId = 14816;
        } else if (blockId == 452) {
            stateId = 14854;
        } else if (blockId == 453) {
            stateId = 14808;
        } else if (blockId == 455) {
            stateId = 14823;
        } else if (blockId == 456) {
            stateId = 14824;
        } else if (blockId == 457) {
            stateId = 14853;
        } else if (blockId == 458) {
            stateId = 14796;
        } else if (blockId == 459) {
            stateId = 14791;
        } else if (blockId == 461) {
            stateId = 14859;
        } else if (blockId == 462) {
            stateId = 14962;
        } else if (blockId == 463) {
            stateId = 14893;
        } else if (blockId == 464) {
            stateId = 14901;
        } else if (blockId == 466) {
            stateId = 15757;
        } else if (blockId == 467) {
            stateId = 110;
        } else if (blockId == 468) {
            stateId = 15759;
        } else if (blockId == 471) {
            stateId = 1423;
        } else if (blockId == 473) {
            stateId = 15784;
        } else if (blockId == 474) {
            stateId = 15808;
        } else if (blockId == 475) {
            stateId = 15832;
        } else if (blockId == 476) {
            stateId = 15833;
        } else if (blockId == 477) {
            stateId = 15846;
        } else if (blockId == 478) {
            stateId = 15052;
        } else if (blockId == 479) {
            stateId = 14981;
        } else if (blockId == 480) {
            stateId = 14984;
        } else if (blockId == 481) {
            stateId = 14967;
        } else if (blockId == 482) {
            stateId = 14980;
        } else if (blockId == 483) {
            stateId = 14996;
        } else if (blockId == 484) {
            stateId = 14979;
        } else if (blockId == 485) {
            stateId = 14997;
        } else if (blockId == 486) {
            stateId = 14998;
        } else if (blockId == 487) {
            stateId = 14995;
        } else if (blockId == 488) {
            stateId = 14978;
        } else if (blockId == 489) {
            stateId = 4003;
        } else if (blockId == 490) {
            stateId = 4006;
        } else if (blockId == 491) {
            stateId = 4001;
        } else if (blockId == 492) {
            stateId = 1952;
        } else if (blockId == 493) {
            stateId = 14982;
        } else if (blockId == 494) {
            stateId = 15768;
        } else if (blockId == 495) {
            stateId = 14987;
        } else if (blockId == 496) {
            stateId = 14970;
        } else if (blockId == 497) {
            stateId = 15053;
        } else if (blockId == 498) {
            stateId = 15054;
        } else if (blockId == 499) {
            stateId = 15546;
        } else if (blockId == 500) {
            stateId = 15610;
        } else if (blockId == 501) {
            stateId = 15150;
        } else if (blockId == 502) {
            stateId = 15214;
        } else if (blockId == 507) {
            stateId = 15728;
        } else if (blockId == 508) {
            stateId = 15736;
        } else if (blockId == 509) {
            stateId = 15338;
        } else if (blockId == 510) {
            stateId = 15418;
        } else if (blockId == 511) {
            stateId = 15102;
        } else if (blockId == 512) {
            stateId = 15134;
        } else if (blockId == 513) {
            stateId = 15270;
        } else if (blockId == 514) {
            stateId = 15302;
        } else if (blockId == 515) {
            stateId = 15496;
        } else if (blockId == 516) {
            stateId = 15520;
        } else if (blockId == 517) {
            stateId = 15068;
        } else if (blockId == 518) {
            stateId = 15070;
        } else if (blockId == 519) {
            stateId = 15058;
        } else if (blockId == 520) {
            stateId = 15064;
        } else if (blockId == 523) {
            stateId = 4008;
        } else if (blockId == 524) {
            stateId = 14897;
        } else if (blockId == 525) {
            stateId = 15834;
        } else if (blockId == 526) {
            stateId = 15835;
        } else if (blockId == 527) {
            stateId = 15837;
        } else if (blockId == 528) {
            stateId = 15847;
        } else if (blockId == 529) {
            stateId = 16259;
        } else if (blockId == 530) {
            stateId = 16279;
        } else if (blockId == 531) {
            stateId = 15859;
        } else if (blockId == 532) {
            stateId = 15931;
        } else if (blockId == 533) {
            stateId = 16351;
        } else if (blockId == 534) {
            stateId = 16261;
        } else if (blockId == 535) {
            stateId = 16260;
        } else if (blockId == 536) {
            stateId = 16672;
        } else if (blockId == 537) {
            stateId = 16255;
        } else if (blockId == 539) {
            stateId = 16265;
        } else if (blockId == 541) {
            stateId = 4732;
        } else if (blockId == 542) {
            stateId = 15025;
        } else if (blockId == 543) {
            stateId = 72;
        } else if (blockId == 544) {
            stateId = 15836;
        } else if (blockId == 545) {
            stateId = 14933;
        } else if (blockId == 546) {
            stateId = 16258;
        } else if (blockId == 547) {
            stateId = 16684;
        } else if (blockId == 548) {
            stateId = 16756;
        } else if (blockId == 550) {
            stateId = 16760;
        } else if (blockId == 551) {
            stateId = 16770;
        } else if (blockId == 552) {
            stateId = 16788;
        } else if (blockId == 553) {
            stateId = 14973;
        } else if (blockId == 554) {
            stateId = 14990;
        } else if (blockId == 555) {
            stateId = 14993;
        } else if (blockId == 556) {
            stateId = 14976;
        } else if (blockId == 557) {
            stateId = 17109;
        } else if (blockId == 558) {
            stateId = 17110;
        } else if (blockId == 559) {
            stateId = 17111;
        }

        return stateId;
    }
}
